### ISSUE TITLE
[BUG] failed to render templates " has no attribute 'counter_width_bits' "

### ISSUE THREAD

**Issue by selahaddinkenco** [ramseymcgrath/PCILeechFWGenerator#207]
```
08:28:01 - INFO -   08:28:01 │  INFO  │ [VFIO] Device 0000:08:00.0 is in IOMMU group 12
08:28:01 - INFO -   08:28:01 │  INFO  │ [VFIO] Successfully obtained device fd 6 for 0000:08:00.0
08:28:01 - WARNING -   08:28:01 │ WARNING│ mmap failed with EINVAL - BAR may not be mappable or accessible
08:28:01 - INFO -   08:28:01 │  INFO  │ Generating default MSI-X table initialization for 4 vectors
08:28:02 - ERROR - Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
08:28:02 - ERROR -   08:28:02 │ ERROR  │ Failed to render SystemVerilog template: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
08:28:02 - ERROR -   08:28:02 │ ERROR  │ PCILeech SystemVerilog generation failed: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
08:28:02 - ERROR -   08:28:02 │ ERROR  │ [PCIL] PCILeech firmware generation failed: SystemVerilog generation failed: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
08:28:02 - ERROR - Build failed: 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
08:28:02 - ERROR - Unexpected error: 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
04:28:02 ERROR Build failed: Command 'podman run --rm --privileged               --device=/dev/vfio/12               --device=/dev/vfio/vfio               --entrypoint python3               --user root               -v /home/tpx/gits/PCILeechFWGenerator/output:/app/output               -v /lib/modules/$(uname -r)/build:/kernel-headers:ro               pcileech-fw-generator:latest               -m src.build --bdf 0000:08:00.0 --board pcileech_pciescreamer_xc7a35' returned non-zero exit status 1.
```
```
=== VFIO DIAGNOSTIC REPORT ===
Overall: ✔ OK
Device : 0000:08:00.0
Proceed: yes

✔ Platform: Linux detected
✔ IOMMU HW: VT‑d / AMD‑Vi supported by CPU
✔ Kernel cmdline: IOMMU enabled in cmdline: intel_iommu=on, iommu=on
✔ ACS bypass: Device isolated in IOMMU group 12
✔ Kernel modules: All VFIO modules loaded: vfio, vfio_pci, vfio_iommu_type1
✔ vfio-pci driver: vfio-pci registered
✔ Device: 0000:08:00.0 (0x10ec:0x8136) present
✔ IOMMU group: Group 12
✔ Driver: Already bound to vfio-pci
✔ /dev/vfio node: /dev/vfio/12

```

[log.txt](https://github.com/user-attachments/files/21594482/log.txt)

**Comment by sthgi** [comment]
same

**Comment by Danielix99** [comment]
I confirm im able to build in 0.9.5 and in 0.9.6 i got this same issue

14:50:00 - INFO -   14:50:00 │  INFO  │ [VFIO] Successfully obtained device fd 6 for 0000:06:00.0
14:50:00 - INFO -   14:50:00 │  INFO  │ Successfully read 128 DWORDs from actual MSI-X table
14:50:00 - INFO -   14:50:00 │  INFO  │ Using actual MSI-X table data from hardware (32 entries)
14:50:00 - ERROR - Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
14:50:00 - ERROR -   14:50:00 │ ERROR  │ Failed to render SystemVerilog template: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
14:50:00 - ERROR -   14:50:00 │ ERROR  │ PCILeech SystemVerilog generation failed: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
14:50:00 - ERROR -   14:50:00 │ ERROR  │ [PCIL] PCILeech firmware generation failed: SystemVerilog generation failed: Failed to render template 'sv/advanced_controller.sv.j2': 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
14:50:00 - ERROR - Build failed: 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'
14:50:00 - ERROR - Unexpected error: 'src.templating.advanced_sv_features.PerformanceConfig object' has no attribute 'counter_width_bits'


=== VFIO DIAGNOSTIC REPORT ===
Overall: ✔ OK
Device : 0000:06:00.0
Proceed: yes

✔ Platform: Linux detected
✔ IOMMU HW: VT‑d / AMD‑Vi supported by CPU
✔ Kernel cmdline: IOMMU enabled in cmdline: intel_iommu=on, iommu=on, ACS override: pcie_acs_override=downstream, pcie_acs_override=downstream,multifunction
✔ Kernel modules: All VFIO modules loaded: vfio, vfio_pci, vfio_iommu_type1
✔ vfio-pci driver: vfio-pci registered
✔ Device: 0000:06:00.0 present
✔ IOMMU group: Group 14
✔ Driver: Already bound to vfio-pci
✔ /dev/vfio node: /dev/vfio/14

**Comment by ghost** [comment]
Same issue for me as well

**Comment by Koxrusty** [comment]
same
